pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - check-success=build
    actions:
      merge:
        method: squash
  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=build
    actions:
      merge:
        method: squash
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - check-success=build
    actions:
      merge:
        method: merge

