name: Generate kiai.js docs

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build and Test
        timeout-minutes: 15
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

        steps:
            - name: Check out code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Generate Docs
              run: pnpm run docs --filter kiai.js

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_branch: kiaijs-docs
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./packages/kiai.js/docs
                  cname: kiai.js.org
